[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0

[font]
size = 15.0

[font.normal]
family = "PixelCode"
style = "Regular"

[font.bold]
family = "PixelCode"
style = "Bold"

[font.italic]
family = "PixelCode"
style = "Italic"

[font.bold_italic]
family = "PixelCode"
style = "Bold Italic"

[colors.primary]
background = "#0c0c0c"
foreground = "#ffffff"

[colors.normal]
black   = "#000000"
red     = "#ff5555"
green   = "#55ff55"
yellow  = "#ffff55"
blue    = "#5555ff"
magenta = "#ff55ff"
cyan    = "#55ffff"
white   = "#ffffff"

[colors.bright]
black   = "#555555"
red     = "#ff5555"
green   = "#55ff55"
yellow  = "#ffff55"
blue    = "#5555ff"
magenta = "#ff55ff"
cyan    = "#55ffff"
white   = "#ffffff"

### Keybinds ###
# Map CTRL for tmux tabs.

# Ctrl + 1
[[keyboard.bindings]]
key = "Key1"
mods = "Control"
chars = "\u001b[27;5;49~"

# Ctrl + 2
[[keyboard.bindings]]
key = "Key2"
mods = "Control"
chars = "\u001b[27;5;50~"

# Ctrl + 3
[[keyboard.bindings]]
key = "Key3"
mods = "Control"
chars = "\u001b[27;5;51~"

# Ctrl + 4
[[keyboard.bindings]]
key = "Key4"
mods = "Control"
chars = "\u001b[27;5;52~"

# Ctrl + 5
[[keyboard.bindings]]
key = "Key5"
mods = "Control"
chars = "\u001b[27;5;53~"

# Ctrl + 6
[[keyboard.bindings]]
key = "Key6"
mods = "Control"
chars = "\u001b[27;5;54~"

# Ctrl + 7
[[keyboard.bindings]]
key = "Key7"
mods = "Control"
chars = "\u001b[27;5;55~"

# Ctrl + 8
[[keyboard.bindings]]
key = "Key8"
mods = "Control"
chars = "\u001b[27;5;56~"

# Ctrl + 9
[[keyboard.bindings]]
key = "Key9"
mods = "Control"
chars = "\u001b[27;5;57~"

# Ctrl + Alt + 1
[[keyboard.bindings]]
key = "Key1"
mods = "Control|Alt"
chars = "\u001b[27;7;49~"

# Ctrl + Alt + 2
[[keyboard.bindings]]
key = "Key2"
mods = "Control|Alt"
chars = "\u001b[27;7;50~"

# Ctrl + Alt + 3
[[keyboard.bindings]]
key = "Key3"
mods = "Control|Alt"
chars = "\u001b[27;7;51~"

# Ctrl + Alt + 4
[[keyboard.bindings]]
key = "Key4"
mods = "Control|Alt"
chars = "\u001b[27;7;52~"

# Ctrl + Alt + 5
[[keyboard.bindings]]
key = "Key5"
mods = "Control|Alt"
chars = "\u001b[27;7;53~"

# Ctrl + Alt + 6
[[keyboard.bindings]]
key = "Key6"
mods = "Control|Alt"
chars = "\u001b[27;7;54~"

# Ctrl + Alt + 7
[[keyboard.bindings]]
key = "Key7"
mods = "Control|Alt"
chars = "\u001b[27;7;55~"

# Ctrl + Alt + 8
[[keyboard.bindings]]
key = "Key8"
mods = "Control|Alt"
chars = "\u001b[27;7;56~"

# Ctrl + Alt + 9
[[keyboard.bindings]]
key = "Key9"
mods = "Control|Alt"
chars = "\u001b[27;7;57~"
